import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

test('WebView panel provides named-project creation and Send-only request controls', async () => {
  const html = await readFile('apps/panel/index.html', 'utf8');
  const script = await readFile('apps/panel/panel.js', 'utf8');

  assert.match(html, /id="workspace-root"/);
  assert.match(html, /id="project-name"/);
  assert.match(html, /id="active-project"/);
  assert.match(html, /aria-label="Active project"/);
  assert.match(html, /id="request-status"/);
  assert.match(html, /aria-label="Request status"/);
  assert.match(html, /id="validation-status"/);
  assert.match(html, /id="inspection-card"/);
  assert.match(html, /id="inspection-freshness"/);
  assert.match(html, /id="inspection-digest"/);
  assert.match(html, /id="inspection-artifact-count"/);
  assert.match(html, /id="inspection-erc"/);
  assert.match(html, /id="inspection-drc"/);
  assert.match(html, /id="approve-patch-button"/);
  assert.match(html, /id="kicad-link"/);
  assert.match(html, /id="recheck-kicad-button"/);
  assert.match(html, /id="conversation-log"/);
  assert.match(html, /id="conversation-options"/);
  assert.doesNotMatch(html, /id="generate-button"/);
  assert.match(script, /project\.create/);
  assert.match(script, /project\.request/);
  assert.match(script, /renderRequestStatus/);
  assert.match(script, /renderValidation/);
  assert.match(script, /renderKiCadLink/);
  assert.match(script, /project\.inspect/);
  assert.match(script, /inspectionState/);
  assert.match(script, /renderInspection/);
  assert.match(script, /patchId/);
  assert.match(script, /expiresAt/);
  assert.match(script, /clearPatchApproval/);
  assert.match(script, /approved: true, patchId: patchApprovalState\.patchId/);
  assert.match(script, /cancel: true, patchId: patchApprovalState\.patchId/);
  assert.match(script, /chatpcbHost/);
  assert.match(script, /hostPathMatchesActive/);
  assert.match(script, /startConflictWatch/);
  assert.match(script, /visibilitychange/);
  assert.match(script, /Circuit request is required/);
  assert.match(script, /operation === 'clarify'/);
  assert.match(script, /linkState !== 'unlinked'/);
  assert.match(script, /KiCad changes need attention/);
  assert.match(script, /showModal/);
  assert.match(script, /hostPathMatchesActive\(pendingHostStatus\.projectPath\)/);
  assert.match(script, /dataset\.help/);
  assert.match(script, /option\.help/);
  assert.match(script, /dataset\.recommended/);
  assert.match(html, /status-dock/);
  assert.match(html, /chat-column/);
  assert.match(html, /id="pro-mode"/);
  assert.match(html, /recommended choice/);
  assert.match(html, /id="new-project-again"/);
  assert.match(html, /styles\.css\?v=/);
  assert.match(html, /panel\.js\?v=/);
  assert.match(script, /proMode/);
  assert.match(script, /renderConversation\(result\)/);
  assert.match(script, /new-project-again/);
});

test('KiCad fork skeleton declares a wxWebView-backed ChatPCB panel', async () => {
  const header = await readFile('kicad-fork/chatpcb_panel/chatpcb_panel.h', 'utf8');
  const implementation = await readFile('kicad-fork/chatpcb_panel/chatpcb_panel.cpp', 'utf8');

  assert.match(header, /class CHATPCB_PANEL/);
  assert.match(header, /wxWebView/);
  assert.match(implementation, /CHATPCB_AGENT_PORT/);
  assert.match(implementation, /LoadURL/);
});
